export interface SetupProps {
  tab: string
  key: string
  name: string
  value: string
}

export const emptySetup: SetupProps[] = [
  {
    tab: 'Setup',
    key: 'FuelSetting',
    name: 'Starting Fuel',
    value: '',
  },
  {
    tab: 'Setup',
    key: 'NumPitstopsSetting',
    name: 'Number of Stop',
    value: '',
  },
  {
    tab: 'Setup',
    key: 'Pitstop1Setting',
    name: 'Stop 1',
    value: '',
  },
  {
    tab: 'Setup',
    key: 'Pitstop2Setting',
    name: 'Stop 2',
    value: '',
  },
  {
    tab: 'Setup',
    key: 'Pitstop3Setting',
    name: 'Stop 3',
    value: '',
  },
  {
    tab: 'Setup',
    key: 'Notes',
    name: 'Notes',
    value: '',
  },
  {
    tab: 'General',
    key: 'Gear1Setting',
    name: 'Gear 1',
    value: '',
  },
  {
    tab: 'General',
    key: 'Gear2Setting',
    name: 'Gear 2',
    value: '',
  },
  {
    tab: 'General',
    key: 'Gear3Setting',
    name: 'Gear 3',
    value: '',
  },
  {
    tab: 'General',
    key: 'Gear4Setting',
    name: 'Gear 4',
    value: '',
  },
  {
    tab: 'General',
    key: 'Gear5Setting',
    name: 'Gear 5',
    value: '',
  },
  {
    tab: 'General',
    key: 'Gear6Setting',
    name: 'Gear 6',
    value: '',
  },
  {
    tab: 'General',
    key: 'Gear7Setting',
    name: 'Gear 7',
    value: '',
  },
  {
    tab: 'General',
    key: 'Gear8Setting',
    name: 'Gear 8',
    value: '',
  },
  {
    tab: 'General',
    key: 'RatioSetSetting',
    name: 'Ratio Set',
    value: '',
  },
  {
    tab: 'General',
    key: 'FinalDriveSetting',
    name: 'Gear Final',
    value: '',
  },
  {
    tab: 'General',
    key: 'ReverseSetting',
    name: 'Gear Reverse',
    value: '',
  },
  {
    tab: 'General',
    key: 'GearAutoUpShiftSetting',
    name: 'Gear Auto Upshift',
    value: '',
  },
  {
    tab: 'General',
    key: 'GearAutoDownShiftSetting',
    name: 'Gear Auto Downshift',
    value: '',
  },
  {
    tab: 'General',
    key: 'SteerLockSetting',
    name: 'Wheel Range (Lock)',
    value: '',
  },
  {
    tab: 'General',
    key: 'DiffPumpSetting',
    name: 'Pump',
    value: '',
  },
  {
    tab: 'General',
    key: 'DiffPowerSetting',
    name: 'Power',
    value: '',
  },
  {
    tab: 'General',
    key: 'DiffCoastSetting',
    name: 'Coast',
    value: '',
  },
  {
    tab: 'General',
    key: 'DiffPreloadSetting',
    name: 'Preload',
    value: '',
  },
  {
    tab: 'General',
    key: 'FWSetting',
    name: 'Front Wing',
    value: '',
  },
  {
    tab: 'General',
    key: 'RWSetting',
    name: 'Rear Wing',
    value: '',
  },
  {
    tab: 'General',
    key: 'FenderFlareSettingLEFTFENDER',
    name: 'Fender Flare Left',
    value: '',
  },
  {
    tab: 'General',
    key: 'FenderFlareSettingRIGHTFENDER',
    name: 'Fender Flare Right',
    value: '',
  },
  {
    tab: 'General',
    key: 'RevLimitSetting',
    name: 'Rev Limiter',
    value: '',
  },
  {
    tab: 'General',
    key: 'EngineMixtureSetting',
    name: 'Engine Mixture',
    value: '',
  },
  {
    tab: 'General',
    key: 'EngineBoostSetting',
    name: 'Boost Mapping',
    value: '',
  },
  {
    tab: 'General',
    key: 'EngineBrakingMapSetting',
    name: 'Brake Map',
    value: '',
  },
  {
    tab: 'General',
    key: 'RadiatorSetting',
    name: 'Radiator',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'Symmetric',
    name: 'Symmetrical',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'Front3rdPackerSetting',
    name: 'Third Packers Front',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'Front3rdSpringSetting',
    name: 'Third Spring Front',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'Front3rdSlowBumpSetting',
    name: 'Third Slow Bymp Front',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'Front3rdFastBumpSetting',
    name: 'Third Fast Bump Front',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'Front3rdSlowReboundSetting',
    name: 'Third Slow Rebound Front',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'Front3rdFastReboundSetting',
    name: 'Third Fast Rebound Front',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'Rear3rdPackerSetting',
    name: 'Third Packers Rear',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'Rear3rdSpringSetting',
    name: 'Third Spring Rear',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'Rear3rdSlowBumpSetting',
    name: 'Third Slow Bump Rear',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'Rear3rdFastBumpSetting',
    name: 'Third Fast Bump Rear',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'Rear3rdSlowReboundSetting',
    name: 'Third Slow Rebound Rear',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'Rear3rdFastReboundSetting',
    name: 'Third Fast Rebound Rear',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'SpringSettingFRONTLEFT',
    name: 'Spring Rate Front Left',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'SpringSettingFRONTRIGHT',
    name: 'Spring Rate Front Right',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'SpringSettingREARLEFT',
    name: 'Spring Rate Rear Left',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'SpringSettingREARRIGHT',
    name: 'Spring Rate Rear Right',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'SlowBumpSettingFRONTLEFT',
    name: 'Slow Bump Front Left',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'SlowBumpSettingFRONTRIGHT',
    name: 'Slow Bump Front Right',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'SlowBumpSettingREARLEFT',
    name: 'Slow Bump Rear Left',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'SlowBumpSettingREARRIGHT',
    name: 'Slow Bump Rear Right',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'SlowReboundSettingFRONTLEFT',
    name: 'Slow Rebound Front Left',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'SlowReboundSettingFRONTRIGHT',
    name: 'Slow Rebound Front Right',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'SlowReboundSettingREARLEFT',
    name: 'Slow Rebound Rear Left',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'SlowReboundSettingREARRIGHT',
    name: 'Slow Rebound Rear Right',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'FastBumpSettingFRONTLEFT',
    name: 'Fast Bump Front Left',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'FastBumpSettingFRONTRIGHT',
    name: 'Fast Bump Front Right',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'FastBumpSettingREARLEFT',
    name: 'Fast Bump Rear Left',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'FastBumpSettingREARRIGHT',
    name: 'Fast Bump Rear Right',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'FastReboundSettingFRONTLEFT',
    name: 'Fast Rebound Fron Left',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'FastReboundSettingFRONTRIGHT',
    name: 'Fast Rebound Front Right',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'FastReboundSettingREARLEFT',
    name: 'Fast Rebound Rear Left',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'FastReboundSettingREARRIGHT',
    name: 'Fast Rebound Rear Right',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'PackerSettingFRONTLEFT',
    name: 'Packers Front Left',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'PackerSettingFRONTRIGHT',
    name: 'Packers Front Right',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'PackerSettingREARLEFT',
    name: 'Packers Rear Left',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'PackerSettingREARRIGHT',
    name: 'Packers Rear Right',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'RideHeightSettingFRONTLEFT',
    name: 'Ride Height Front Left',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'RideHeightSettingFRONTRIGHT',
    name: 'Ride Height Front Right',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'RideHeightSettingREARLEFT',
    name: 'Ride Height Rear Left',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'RideHeightSettingREARRIGHT',
    name: 'Ride Height Rear Right',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'FrontAntiSwaySetting',
    name: 'Anti-Roll Bar Front',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'RearAntiSwaySetting',
    name: 'Anti-Roll Bar Rear',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'FrontToeInSetting',
    name: 'Toe In Front',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'RearToeInSetting',
    name: 'Toe In Rear',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'FrontToeOffsetSetting',
    name: 'Front Toe Offset',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'RearToeOffsetSetting',
    name: 'Rear Toe Offset',
    value: '',
  },
  {
    tab: 'Suspension',
    key: 'RearSplitSetting',
    name: 'Torque Split',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'FenderFlareSettingLEFTFENDER',
    name: 'Fender Flare Left',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'FenderFlareSettingRIGHTFENDER',
    name: 'Fender Flare Right',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'LeftTrackBarSetting',
    name: 'Track Bar Left',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'RightTrackBarSetting',
    name: 'Track Bar Right',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'LeftCasterSetting',
    name: 'Caster Left',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'RightCasterSetting',
    name: 'Caster Right',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'ChassisAdj00Setting',
    name: 'Chassis Adjustment 1',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'ChassisAdj01Setting',
    name: 'Chassis Adjustment 2',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'ChassisAdj02Setting',
    name: 'Chassis Adjustment 3',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'ChassisAdj03Setting',
    name: 'Chassis Adjustment 4',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'ChassisAdj04Setting',
    name: 'Chassis Adjustment 5',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'ChassisAdj05Setting',
    name: 'Chassis Adjustment 6',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'ChassisAdj06Setting',
    name: 'Chassis Adjustment 7',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'ChassisAdj07Setting',
    name: 'Chassis Adjustment 8',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'ChassisAdj08Setting',
    name: 'Chassis Adjustment 9',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'ChassisAdj09Setting',
    name: 'Chassis Adjustment 10',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'ChassisAdj10Setting',
    name: 'Chassis Adjustment 11',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'ChassisAdj11Setting',
    name: 'Chassis Adjustment 12',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'FrontWheelTrackSetting',
    name: 'Front Wheel Track',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'RearWheelTrackSetting',
    name: 'Rear Wheel Track',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'CGRightSetting',
    name: 'Lateral',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'CGHeightSetting',
    name: 'Vertical',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'WedgeSetting',
    name: 'Wedge',
    value: '',
  },
  {
    tab: 'Chassis',
    key: 'CGRearSetting',
    name: 'Weight Dist',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'Symmetric',
    name: 'Symmetrical',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'PressureSettingFRONTLEFT',
    name: 'Tyre Pressure Front Left',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'PressureSettingFRONTRIGHT',
    name: 'Tyre Pressure Front Right',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'PressureSettingREARLEFT',
    name: 'Tyre Pressure Rear Left',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'PressureSettingREARRIGHT',
    name: 'Tyre Pressure Rear Right',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'FrontTireCompoundSetting',
    name: 'Front Tire Compound',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'RearTireCompoundSetting',
    name: 'Rear Tire Compound',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'CamberSettingFRONTLEFT',
    name: 'Camber Front Left Tire',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'CamberSettingFRONTRIGHT',
    name: 'Camber Front Right Tire',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'CamberSettingREARLEFT',
    name: 'Camber Rear Left Tire',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'CamberSettingREARRIGHT',
    name: 'Camber Rear Right Tire',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'RearBrakeSetting',
    name: 'Brake Bias',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'BrakeDuctSetting',
    name: 'Brake Duct Blanking',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'BrakePressureSetting',
    name: 'Max Pedal Force',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'HandbrakePressSetting',
    name: 'Handbrake Pressure',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'BrakeDiscSettingFRONTLEFT',
    name: 'Brake Disc Front Left',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'BrakeDiscSettingFRONTRIGHT',
    name: 'Brake Disc Front Right',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'BrakeDiscSettingREARLEFT',
    name: 'Brake Disc Rear Left',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'BrakeDiscSettingREARRIGHT',
    name: 'Brake Disc Rear Right',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'TCSetting',
    name: 'Traction Control',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'ABSSetting',
    name: 'Anti-Lock Brakes',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'TractionControlMapSetting',
    name: 'Traction Control Map',
    value: '',
  },
  {
    tab: 'Advanced',
    key: 'AntilockBrakeSystemMapSetting',
    name: 'Antilock Brake System Map',
    value: '',
  },
]
