name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install # will run `yarn install` command

    - name: Lint React files
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: lint # will run `yarn lint` command

    - name: Lint CSS files
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: lintcss # will run `yarn lintcss` command

    - name: Build app
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build # will run `yarn build` command

    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: Sergih28@users.noreply.github.com
        build_dir: build
